import "./files/gif";
import "./files/jpeg";
import "./files/jpg";
import "./files/png";
import "./files/svg";
import "./files/webp";
import "./files/styles";
import "./vendors-manifest";
import "./common/ssrData";
import "./common/response";
import "./core";
import "./window";

import UserDto from "backend/dto/userDto";

declare global {
  namespace Express {
    interface Response {
      /**
       * Renders bundle to html, then sends it
       * or performs redirect if necessary
       */
      // tslint:disable-next-line:no-any
      renderBundle(bundleName: string, data?: ServerData): void;
    }

    interface Request {
      /**
       * Cryptographic nonce which is used to mark scripts as approved,
       * generated by express-yandex-csp middleware
       *
       * More about CSP headers:
       * https://content-security-policy.com/
       * https://www.w3.org/TR/CSP3/
       */
      nonce: string;

      user: UserDto;
    }
  }
}
